services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achadinhos
      - MYSQL_USER=neves
      - MYSQL_PASSWORD=12qwaszx
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

volumes:
  mysql_data:

networks:
  app:
    driver: bridge
