services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --save 900 1
      --save 300 10
      --save 60 10000
      --dir /data
      --dbfilename dump.rdb
      --appendonly yes
      --appendfsync everysec
    networks:
      - app

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achadinhos
      - MYSQL_USER=neves
      - MYSQL_PASSWORD=12qwaszx
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

volumes:
  redis_data:
  mysql_data:

networks:
  app:
    driver: bridge
